theme: jekyll-theme-midnight
title: Calzone Breaks Things
description: Exploring memory, reverse engineering, and fuzzing.
show_downloads: false

plugins:
- jekyll-remote-theme
- jekyll-sitemap
- jekyll-feed
